version: '3.9'

services:
  dot-game:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4173:4173
    environment:
      - NODE_ENV=development
    networks:
      - dot-game-network

  stats:
    image: registry.mesgexchange.io/stats:latest
    volumes:
      - stats-data:/app/data
    networks:
      - dot-game-network
    ports:
      - '5775:5775'
    restart: unless-stopped

volumes:
  stats-data:

networks:
  dot-game-network:
    driver: bridge
