version: '3.9'

services:
  dot-game:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    networks:
      - dot-game-network

networks:
  dot-game-network:
    driver: bridge
